MyFirstWebApplication/MyFirstWebApplication/Models/ExchangeRate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MyFirstWebApplication.Models
{
    public class ExchangeRate<T>

    {
        public ExchangeRate(string currencyName, int multiplier, T code, decimal rate)
        {
            //if (rate < 0.1m)
            //    throw new VeryLowRateException(currencyName);

            CurrencyName = currencyName;
            Multiplier = multiplier;
            CurrencyCode = code;
            Rate = rate;
        }


        public string CurrencyName { get; private set; }


        public int Multiplier { get; private set; }


        public T CurrencyCode { get; private set; }

  
        public decimal Rate { get; private set; }

        public override string ToString()
        {
            return string.Format("Waluta: {0}, Kod waluty: {1}, Kurs wymiany: {2:F3}, Multiplier: {3}", CurrencyName, CurrencyCode, Rate, Multiplier);
        }
    }
}

MyFirstWebApplication/MyFirstWebApplication/Models/ExchangeRatesProvider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Xml;

namespace MyFirstWebApplication.Models
{
    public class ExchangeRatesProvider
    {
        private static List<ExchangeRate<string>> _cache;
        public List<ExchangeRate<string>> CreateExchangeRates()
        {
            if (_cache == null)
            {
                var exchangeRates = new List<ExchangeRate<string>>();
                XmlReader r = XmlReader.Create(@"https://www.nbp.pl/kursy/xml/a194z181005.xml");
                using (r)

                {
                    while (r.Read())
                    {
                        if (r.Name == "pozycja" && r.IsStartElement())
                        {
                            r.ReadToFollowing("nazwa_waluty");
                            var currencyName = r.ReadElementContentAsString();
                            r.ReadToFollowing("przelicznik");
                            var multiplier = r.ReadElementContentAsObject();
                            r.ReadToFollowing("kod_waluty");
                            var currencyType = r.ReadElementContentAsString();
                            r.ReadToFollowing("kurs_sredni");
                            decimal rate = decimal.Parse((r.ReadElementContentAsObject()).ToString());

                            ExchangeRate<string> ex = new ExchangeRate<string>(currencyName,
                                int.Parse((multiplier).ToString()), currencyType, rate);
                            exchangeRates.Add(ex);
                        }
                    }
                }

                _cache = exchangeRates;
            }

            return _cache;
        }

        public void AddNew(ExchangeRate<string> newRate)
        {
            _cache.Add(newRate);
        }
    }
}

MyFirstWebApplication/MyFirstWebApplication/ViewModels/NewExchangeRateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MyFirstWebApplication.ViewModels
{
    public class NewExchangeRateViewModel
    {
        [DisplayName("Nazwa waluty")]
        public string CurrencyName { get; set; }
        [DisplayName("Kod waluty")]
        public string CurrencyCode { get; set; }
        [DisplayName("Kurs wymiany")]
        public double Rate {get; set; }

        [DisplayName("Mnożnik")]
        public int Multiplier { get; set; }
    }
}

MyFirstWebApplication/MyFirstWebApplication/Controllers/ExchangeRatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFirstWebApplication.Models;
using MyFirstWebApplication.ViewModels;

namespace MyFirstWebApplication.Controllers
{
    public class ExchangeRatesController : Controller
    {
        // GET: ExchangeRates
        public ActionResult Index()
        {
            var provider = new ExchangeRatesProvider();
            var exchangeRates = provider.CreateExchangeRates();
            return View(exchangeRates);
        }

        public ActionResult Details(string currencyCode)
        {
            if (string.IsNullOrWhiteSpace(currencyCode))
                return View();

            var provider = new ExchangeRatesProvider();
            var exchangeRate = provider.CreateExchangeRates().FirstOrDefault(x=>x.CurrencyCode == currencyCode);

            if (exchangeRate == null)
                return View();

            return View(exchangeRate);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(NewExchangeRateViewModel newRate)
        {
            if (ModelState.IsValid == false)
                return View(newRate);

            var provider = new ExchangeRatesProvider();
            provider.AddNew(new ExchangeRate<string>(newRate.CurrencyName, 
                                                     newRate.Multiplier, 
                                                     newRate.CurrencyCode,
                                                     (decimal)newRate.Rate));
            return RedirectToAction("Index");
        }
    }
}

MyFirstWebApplication/MyFirstWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public string Message { get; set; }
        public ActionResult Index()
        {
            Message = "Index";
            var model = new int[] {1, 3, 5, 7}.ToList();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.!" + Message;

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult NewAction(int id)
        {
            return View(id);
        }
    }
}

MyFirstWebApplication/MyFirstWebApplication/Views/ExchangeRates/Add.cshtml
@model MyFirstWebApplication.ViewModels.NewExchangeRateViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Dodawanie nowego kursu wymiany</h2>

@*<form action="/ExchangeRates/Add"></form>*@

@using(Html.BeginForm("Add", "ExchangeRates", FormMethod.Post)) 
{
    <p>@Html.LabelFor(m=>m.CurrencyName)</p>
    <p>@Html.TextBoxFor(m => m.CurrencyName)</p>
    <p>@Html.LabelFor(m=>m.CurrencyCode)</p>
    <p>@Html.TextBoxFor(m=>m.CurrencyCode)</p>

    <p>@Html.LabelFor(m=>m.Rate)</p>
    <p>@Html.TextBoxFor(m => m.Rate)</p>
    <p>@Html.LabelFor(m=>m.Multiplier)</p>
    <p>@Html.TextBoxFor(m=>m.Multiplier)</p>

    <input type="submit" value="Dodaj kurs wymiany"/>
}

MyFirstWebApplication/MyFirstWebApplication/Views/ExchangeRates/Details.cshtml
@model MyFirstWebApplication.Models.ExchangeRate<string>
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@if (Model == null)
{
    <p>Nieprawidłowy kod waluty!</p>
}
else
{
    <div>
        <p>nazwa waluty:</p><p>@Model.CurrencyName</p><br />
        <p>kod waluty:</p><p>@Model.CurrencyCode</p><br />
        <p>Kurs wymiany:</p><p>@Model.Rate</p><br />
        <p>Mnożnik:</p><p>@Model.Multiplier</p>
    </div>
}

MyFirstWebApplication/MyFirstWebApplication/Views/ExchangeRates/Index.cshtml
@model List<MyFirstWebApplication.Models.ExchangeRate<string>>

@{
    ViewBag.Title = "Exchange rates list";
}

<h2>Exchange rates list</h2>
@Html.ActionLink("Dodaj kurs wymiany", "Add")
<table>
    <thead>
    <tr>
        <th>Nazwa waluty</th>
        <th>Kod waluty</th>
        <th>Kurs</th>
        <th>Mnożnik</th>
    </tr>
    </thead>
    <tbody>
    @{
        int i = 0;
    }
    @foreach (var ex in Model)
    {
        string style = i % 2 == 0 ? "background-color: white" : "background-color: lightgray";
        <tr style="@style">
            <td>@ex.CurrencyName</td><td>@Html.ActionLink(ex.CurrencyCode, "Details", new { currencyCode = ex.CurrencyCode})</td><td>@ex.Rate</td><td>@ex.Multiplier</td>
        </tr>
        i++;
    }
    </tbody>
</table>

MyFirstWebApplication/MyFirstWebApplication/Views/Home/About.cshtml
@{

    string GetEmail()
    {
        return "a@a.pl";
    }
    ViewBag.Title = "About";
    string email = GetEmail();
    var dict = new Dictionary<string, int>();
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@if (email.EndsWith(".pl"))
{
    <p>Użyj tego obszaru aby dać dodatkowy feedback!</p>
}
else
{
    <p>Use this area to provide additional information. @email</p>
}
@section NavigationLinks {
    <a href="https://pl.lmgtfy.com/?q=help" target="_blank">Pomoc</a>
}

@section scripts {
    <script type="text/javascript" language="javascript">
        alert("ok");
    </script>
}

MyFirstWebApplication/MyFirstWebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyFirstWebApplication/MyFirstWebApplication/Views/Home/Index.cshtml
@model List<int>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
@foreach (var item in Model)
{
    <a href="/Home/NewAction?id=@item">@item</a>
}

MyFirstWebApplication/MyFirstWebApplication/Views/Home/NewAction.cshtml
@model int
@{
    ViewBag.Title = "Nowa akcja";
}

<h2>Nowa akcja:</h2>

<h3>Wybrana opcja to: @Model</h3>

MyFirstWebApplication/MyFirstWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Kantor", "Index", "ExchangeRates")</li>
                </ul>
            </div>
            @RenderSection("NavigationLinks", false)
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>